
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RelianceMkt.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CENTRAL_BLAST
{

    public int Sr_Id { get; set; }

    public string Name { get; set; }

    public string Contact_Number { get; set; }

    public string Type_Of_Data { get; set; }

    public Nullable<int> L1_Code { get; set; }

    public string L1_Name { get; set; }

    public string Channel { get; set; }

    public string CampaignName { get; set; }

}

}
