
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RelianceMkt.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ENGAGE_SHARECOUNT
{

    public decimal SHC_ID { get; set; }

    public string SHC_SAPCODE { get; set; }

    public string SHC_PLATEFORM { get; set; }

    public Nullable<decimal> SHC_SHARECOUNT { get; set; }

    public Nullable<System.DateTime> SHC_DATE { get; set; }

    public Nullable<decimal> CREATIVE_ID { get; set; }

}

}
