
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RelianceMkt.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Lead
{

    public decimal leads_id { get; set; }

    public string leads_name { get; set; }

    public Nullable<decimal> leads_mobile { get; set; }

    public string leads_sapcode { get; set; }

    public Nullable<decimal> leads_creativeid { get; set; }

    public Nullable<System.DateTime> leads_date { get; set; }

    public string leads_plateform { get; set; }

    public string leads_email { get; set; }

    public string api_leads_id { get; set; }

}

}
