

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RelianceMkt.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class rglinixm_relEntities : DbContext
{
    public rglinixm_relEntities()
        : base("name=rglinixm_relEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<campaign> campaigns { get; set; }

    public DbSet<campaign_category> campaign_category { get; set; }

    public DbSet<subcampaign> subcampaigns { get; set; }

    public DbSet<authentication> authentications { get; set; }

    public DbSet<landingpage> landingpages { get; set; }

    public DbSet<Digimyin_Send_Campaign> Digimyin_Send_Campaign { get; set; }

    public DbSet<ENGAGE_SHARECOUNT> ENGAGE_SHARECOUNT { get; set; }

    public DbSet<CENTRAL_BLAST> CENTRAL_BLAST { get; set; }

    public DbSet<campaign_master> campaign_master { get; set; }

    public DbSet<channel> channels { get; set; }

    public DbSet<UserNotification> UserNotifications { get; set; }

    public DbSet<CampaignRespons> CampaignResponses { get; set; }

    public DbSet<NEW_TEMP_HIERARCHY> NEW_TEMP_HIERARCHY { get; set; }

    public DbSet<Lead> Leads { get; set; }

}

}

