
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RelianceMkt.Models
{

using System;
    using System.Collections.Generic;
    
public partial class NEW_TEMP_HIERARCHY
{

    public int ID { get; set; }

    public string X_CHANNEL { get; set; }

    public string X_BM_EMP_CD { get; set; }

    public string X_BM_NM { get; set; }

    public string X_BRANCH { get; set; }

    public string X_REGION { get; set; }

    public string X_SALES_UNIT_CD { get; set; }

    public string X_SALES_UNIT_NM { get; set; }

    public string X_ZM_EMP_CD { get; set; }

    public string X_ZM_NM { get; set; }

    public string X_ZONE { get; set; }

    public string X_RM_EMP_EMP_CD { get; set; }

    public string X_RM_NM { get; set; }

    public string X_SM_EMP_CD { get; set; }

    public string X_SM_NM { get; set; }

    public string X_SM_STATUS { get; set; }

    public string SUBCHANNEL { get; set; }

    public string AGENT_CODE { get; set; }

    public string AGENT_NAME { get; set; }

    public string BM_NAME { get; set; }

    public string ZM_NAME { get; set; }

    public string X_CHANNEL_DESC { get; set; }

}

}
