
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RelianceMkt.Models
{

using System;
    using System.Collections.Generic;
    
public partial class UserNotification
{

    public int NotificationId { get; set; }

    public string SAPCode { get; set; }

    public string Channel_code { get; set; }

    public string Message { get; set; }

    public Nullable<bool> IsRead { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

}

}
