
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RelianceMkt.Models
{

using System;
    using System.Collections.Generic;
    
public partial class authentication
{

    public decimal au_id { get; set; }

    public string au_username { get; set; }

    public string au_password { get; set; }

    public string au_delflag { get; set; }

    public string Role { get; set; }

    public string Subchannel { get; set; }

}

}
