
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RelianceMkt.Models
{

using System;
    using System.Collections.Generic;
    
public partial class campaign_category
{

    public decimal campaign_category_id { get; set; }

    public string campaign_category_name { get; set; }

    public string campaign_category_delflag { get; set; }

    public string Campaign_Category_Status { get; set; }

}

}
