
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RelianceMkt.Models
{

using System;
    using System.Collections.Generic;
    
public partial class channel
{

    public decimal channel_id { get; set; }

    public string channel_name { get; set; }

    public string channel_delflag { get; set; }

    public string subchannel_name { get; set; }

}

}
