
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RelianceMkt.Models
{

using System;
    using System.Collections.Generic;
    
public partial class subcampaign
{

    public decimal subcampaign_id { get; set; }

    public string subcampaign_name { get; set; }

    public Nullable<decimal> campaign_id { get; set; }

    public string subcampaign_delflag { get; set; }

}

}
