
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RelianceMkt.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CampaignRespons
{

    public int Id { get; set; }

    public string Mobile { get; set; }

    public string CampaignName { get; set; }

    public string Response { get; set; }

    public System.DateTime CreatedDate { get; set; }

}

}
