
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RelianceMkt.Models
{

using System;
    using System.Collections.Generic;
    
public partial class campaign_master
{

    public decimal campaign_master_id { get; set; }

    public string campaign_master_code { get; set; }

    public Nullable<decimal> channel_id { get; set; }

    public Nullable<decimal> campaign_category_id { get; set; }

    public Nullable<decimal> subcampaign_id { get; set; }

    public Nullable<decimal> campaign_id { get; set; }

    public string campaign_master_type { get; set; }

    public string campaign_master_lang { get; set; }

    public string campaign_master_description { get; set; }

    public string campaign_master_creative_caption { get; set; }

    public string campaign_master_landing_page { get; set; }

    public Nullable<System.DateTime> campaign_master_start_date { get; set; }

    public Nullable<System.DateTime> campaign_master_end_date { get; set; }

    public Nullable<bool> campaign_master_instagram { get; set; }

    public Nullable<bool> campaign_master_facebook { get; set; }

    public Nullable<bool> campaign_master_twitter { get; set; }

    public Nullable<bool> campaign_master_whatsapp { get; set; }

    public Nullable<decimal> user_id { get; set; }

    public string campaign_master_tags { get; set; }

    public string campaign_master_images { get; set; }

    public Nullable<System.DateTime> campaign_master_date { get; set; }

    public Nullable<bool> campaign_master_linkedin { get; set; }

    public string camapaign_master_status { get; set; }

    public Nullable<bool> input_email { get; set; }

    public Nullable<bool> input_mobile { get; set; }

    public Nullable<bool> input_name { get; set; }

    public string ChannelName { get; set; }

    public string CampaignName { get; set; }

    public string CentralBlast { get; set; }

    public string channel_code { get; set; }

}

}
