
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RelianceMkt.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Digimyin_Send_Campaign
{

    public int ID { get; set; }

    public Nullable<int> Campaign_Master_Id { get; set; }

    public string Name { get; set; }

    public Nullable<long> Contact_Number { get; set; }

    public string Type_Of_Data { get; set; }

    public string L1_Code { get; set; }

    public string L1_Name { get; set; }

    public string Channel { get; set; }

    public Nullable<System.DateTime> Created { get; set; }

    public Nullable<int> Status { get; set; }

    public Nullable<System.DateTime> Updated { get; set; }

}

}
